services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./www/:/var/www/html:rw
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - db
      - php
    networks:
      - brk-network
  php:
    build:
      context: .
      dockerfile: dockerfile
    container_name: php
    restart: unless-stopped
    volumes:
      - ./www/:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_NAME=${DATABASENAME}
      - WORDPRESS_DB_USER=${DATABASEUSER}
      - WORDPRESS_DB_PASSWORD=${DATABASEPASS}
    command: > 
      bash -c "chown -R www-data:www-data /var/www/html 
      && php-fpm"
    networks:
      - brk-network
  db:
    image: mariadb:latest
    container_name: db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=${DATABASENAME}
      - MYSQL_USER=${DATABASEUSER}
      - MYSQL_PASSWORD=${DATABASEPASS}
      - MYSQL_ROOT_PASSWORD=rootpassword
    volumes:
      - brk_data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - brk-network
networks:
  brk-network:
    driver: bridge
volumes:
  brk_data:
